### ISSUE TITLE
QR code and link do not appear

### ISSUE THREAD

**Issue by aradis** [google/wwgc#4]
**Page:**

https://vr.google.com/cardboard/viewerprofilegenerator/

**Expected Result:**

QR code and link will appear

**Actual Result:**

QR code and link do not appear

**Description:**

This URL is requested when loading the page:

https://auth.firebase.com/v2/wwgc/auth/anonymous?v=js-2.0.4&transport=json&suppress_status_codes=true

It returns:

`410 Gone`
`{"code":"SERVICE_UNAVAILABLE","statusCode":410,"message":"SDK Update Required: See https://goo.gl/2cKQWm.","details":"SDK Update Required: https://goo.gl/2cKQWm. "}`

Clicking the `Generate Profile` button also gives a Firebase error.

**Comment by Mourdraug** [comment]
Afaik, google dropped support for Firebase api v2 auth, so this tool is now broken until someone migrates it to new version.

**Comment by sewasewa777** [comment]
#4

**Comment by jellzone** [comment]
OMG, that bug takes a long time!

**Comment by sigmaxipi** [comment]
The site has been updated.
